
version: '3'

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    volumes:
      - data-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dscp-matchmaker-api
volumes:
  data-storage: